---
driver:
  name: rackspace
  require_chef_omnibus: '11.8.2'
  rackspace_username: <%= ENV['rackspace_username'] %>
  rackspace_api_key:  <%= ENV['rackspace_api_key'] %>
  rackspace_region: <%= ENV['rackspace_region'] %>
  public_key_path: <%= ENV['sshpubkey'] %>
  ssh_key: <%= ENV['ssh_key'] %>

platforms:
- name: centos-6.4
  driver_config:
    image_id: 'f70ed7c7-b42e-4d77-83d8-40fa29825b85'
  run_list:
    - recipe[rackspace_yum]
- name: ubuntu-12.04
  driver_config:
    image_id: '80fbcb55-b206-41f9-9bc2-2dd7aac6c061'
  run_list:
  - recipe[rackspace_apt]
- name: debian-7.2
  driver_config:
    image_id: '857d7d36-34f3-409f-8435-693e8797be8b'
  run_list:
    - recipe[rackspace_apt]

suites:
  - name: gerrit
    run_list:
     - recipe[rackspace_apt]
     - recipe[rackspace_build_essential]
     - recipe[rackspace_gerrit]
    attributes:
      rackspace_mysql:
        server_debian_password: 'password'
        server_root_password: 'password'
        server_repl_password: 'password'
      gerrit:
        server_aliases: 'gerrit gerrit2'
      rackspace_apache:
        log_dir: '/var/log/apache2'
        enable_mod_proxy: 'true'

